experience_index:
    path:     /
    defaults: { _controller: "DrAdminBundle:Experience:index" }
    methods:  GET

experience_show:
    path:     /{id}/show
    defaults: { _controller: "DrAdminBundle:Experience:show" }
    methods:  GET

experience_new:
    path:     /new
    defaults: { _controller: "DrAdminBundle:Experience:new" }
    methods:  [GET, POST]

experience_edit:
    path:     /{id}/edit
    defaults: { _controller: "DrAdminBundle:Experience:edit" }
    methods:  [GET, POST]

experience_delete:
    path:     /{id}/delete
    defaults: { _controller: "DrAdminBundle:Experience:delete" }
    methods:  DELETE
