<?php

namespace DrAdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    /**
     * Liste les 10 derniers articles créés
     *
     * @return array
     */
    public function findLastOrderByDate()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT a FROM DrAdminBundle:Article a ORDER BY a.createdAt DESC')
            ->setMaxResults(10)
            ->getResult();
    }
}
