<?php

namespace DrAdminBundle\Repository;

/**
 * PublishStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublishStateRepository extends \Doctrine\ORM\EntityRepository
{
}
